# Railway Deployment Configuration
# This file tells Railway how to deploy your Go backend

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./main"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8080"